export enum MoodType {
  AMAZEMENT = "驚愕",
  SURPRISE = "サプライズ",
  EXCITEMENT = "ワクワク",
  JOY = "喜び",
  SATISFACTION = "満足",
  HAPPINESS = "嬉しい",
  BLESSED = "幸せ",
  RELIEF = "安心",
  FULFILLMENT = "充実感",
  RELAXED = "リラックス",
  PEACEFUL = "穏やか",
  CALM = "冷静",
  DAZED = "ぼんやり",
  BORED = "退屈",
  TIRED = "疲れた",
  SLUGGISH = "だるい",
  SAD = "悲しい",
  DEPRESSED = "憂鬱",
  MISERABLE = "惨め",
  DISAPPOINTED = "がっかり",
  IRRITATED = "いらいら",
  FEAR = "恐怖",
  NERVOUS = "緊張",
  ANGRY = "怒り"
}

export const MoodFoodPairings: Record<MoodType, string> = {
  [MoodType.AMAZEMENT]: "ハッカ飴",
  [MoodType.SURPRISE]: "ソーダ",
  [MoodType.EXCITEMENT]: "パインのかき氷",
  [MoodType.JOY]: "いちごアイス",
  [MoodType.SATISFACTION]: "唐揚げ",
  [MoodType.HAPPINESS]: "チョコレート",
  [MoodType.BLESSED]: "バニラケーキ",
  [MoodType.RELIEF]: "ローズゼリー",
  [MoodType.FULFILLMENT]: "焼き芋",
  [MoodType.RELAXED]: "ミックスナッツ",
  [MoodType.PEACEFUL]: "ジャスミン茶",
  [MoodType.CALM]: "ホットティー",
  [MoodType.DAZED]: "牛乳",
  [MoodType.BORED]: "水",
  [MoodType.TIRED]: "コーヒー",
  [MoodType.SLUGGISH]: "たばこ",
  [MoodType.SAD]: "米酢",
  [MoodType.DEPRESSED]: "ワイン",
  [MoodType.MISERABLE]: "ゴーヤサラダ",
  [MoodType.DISAPPOINTED]: "ビール",
  [MoodType.IRRITATED]: "薬膳スープ",
  [MoodType.FEAR]: "？きのこスープ",
  [MoodType.NERVOUS]: "わさび",
  [MoodType.ANGRY]: "激辛麻婆豆腐"
}; 