export enum Mood {
  AMAZEMENT = "驚愕",
  SURPRISE = "サプライズ",
  EXCITEMENT = "ワクワク",
  JOY = "喜び",
  SATISFACTION = "満足",
  HAPPINESS = "嬉しい",
  BLESSED = "幸せ",
  RELIEF = "安心",
  FULFILLMENT = "充実感",
  RELAXED = "リラックス",
  PEACEFUL = "穏やか",
  CALM = "冷静",
  DAZED = "ぼんやり",
  BORED = "退屈",
  TIRED = "疲れた",
  SLUGGISH = "だるい",
  SAD = "悲しい",
  DEPRESSED = "憂鬱",
  MISERABLE = "惨め",
  DISAPPOINTED = "がっかり",
  IRRITATED = "いらいら",
  FEAR = "恐怖",
  NERVOUS = "緊張",
  ANGRY = "怒り",
}

export const MoodFoodPairings: Record<Mood, string> = {
  [Mood.AMAZEMENT]: "ハッカ飴",
  [Mood.SURPRISE]: "ソーダ",
  [Mood.EXCITEMENT]: "パインのかき氷",
  [Mood.JOY]: "いちごアイス",
  [Mood.SATISFACTION]: "唐揚げ",
  [Mood.HAPPINESS]: "チョコレート",
  [Mood.BLESSED]: "バニラケーキ",
  [Mood.RELIEF]: "ローズゼリー",
  [Mood.FULFILLMENT]: "焼き芋",
  [Mood.RELAXED]: "ミックスナッツ",
  [Mood.PEACEFUL]: "ジャスミン茶",
  [Mood.CALM]: "ホットティー",
  [Mood.DAZED]: "牛乳",
  [Mood.BORED]: "水",
  [Mood.TIRED]: "コーヒー",
  [Mood.SLUGGISH]: "たばこ",
  [Mood.SAD]: "米酢",
  [Mood.DEPRESSED]: "ワイン",
  [Mood.MISERABLE]: "ゴーヤサラダ",
  [Mood.DISAPPOINTED]: "ビール",
  [Mood.IRRITATED]: "薬膳スープ",
  [Mood.FEAR]: "きのこスープ",
  [Mood.NERVOUS]: "わさび",
  [Mood.ANGRY]: "激辛麻婆豆腐",
};
